### ISSUE TITLE
Are there any plans for static localizable string indexing?

### ISSUE THREAD

**Issue by isaac-weisberg** [RxSwiftCommunity/RxLocalizer#12]
So that there is no hard-code strings and compile time checks, R.swift/Swiftgen esque?

**Comment by khambir** [comment]
@isaac-weisberg in any case you can get an identifier of the generated enum case and use the identifier for RxLocalizer.

```
extension LocalizerType {
    public func localize(_ text: Text) -> String {
        return localized(text.string)
    }
    
    public func localize(_ text: Text) -> Driver<String> {
        return localized(text.string)
    }
}
```

Here `Text` enum is a generated enum by the Swiftgen and `string` property is an identifier which you use in a `.strings` file.

**Comment by isaac-weisberg** [comment]
Oh that's nice
