### ISSUE TITLE
source of the older version  from cocoapods

### ISSUE THREAD

**Issue by mkjwa** [RxSwiftCommunity/RxLocalizer#13]
I pulled from CocoaPods. I think it's the older version but it's status is 1.3.0.
So, Could you check it out the proper version can be pulled?
The current version I pulled from cocoaPods  cannot not use the below method.

func localized(_ string: String, arguments: CVarArg...) -> Driver<String>

Thanks,
ps. RxLocalizer is very helpful for me.

**Comment by khambir** [comment]
Hello @mkjwa 

Thanks for notifying me about the issue.
I have just created a new version, which supports the String Interpolation feature.

>  🎉  Congrats
 >🚀  RxLocalizer (1.4.0) successfully published
 >📅  November 22nd, 10:05
 >🌎  https://cocoapods.org/pods/RxLocalizer
 >👍  Tell your friends!

So, you should just call `pod update RxLocalizer` and everything should work as expected.
