### ISSUE TITLE
TextField placeholder

### ISSUE THREAD

**Issue by meyusufdemirci** [RxSwiftCommunity/RxLocalizer#15]
There is no variable for placeholder of TextField

**Comment by meyusufdemirci** [comment]
Opened issue and waiting for pr approve.
https://github.com/ReactiveX/RxSwift/issues/2190

**Comment by khambir** [comment]
Hi @demirciy. How does this issue touch RxLocalizer? You can use localizer for localized any text and UITextField placeholder - one of them

**Comment by meyusufdemirci** [comment]
It does not touch RxLocalizer. RxSwift 6 will cover placeholder, so people can use textfield placeholder with RxLocalizer. You can close the issue, thanks.
